# Generated by Django 5.1.1 on 2024-10-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('lasttime_enter', models.TimeField()),
                ('lastdate_enter', models.DateField()),
                ('services', models.CharField(max_length=255)),
                ('checks', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Analizator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analizator_date', models.DateField()),
                ('analizator_time', models.TimeField()),
                ('analizator_complete_date', models.DateField()),
                ('analizator_complete_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ensurance_company', models.CharField(max_length=50)),
                ('ensurance_adress', models.CharField(max_length=255)),
                ('ensurance_INN', models.IntegerField(max_length=20)),
                ('ensurance_RS', models.IntegerField(max_length=20)),
                ('ensurance_BIK', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Laborants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('lasttime_enter', models.TimeField()),
                ('lastdate_enter', models.DateField()),
                ('services', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('services', models.CharField(max_length=255)),
                ('order_status', models.CharField(max_length=50)),
                ('order_service_status', models.CharField(max_length=50)),
                ('order_complete_days', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('passport', models.IntegerField(max_length=15)),
                ('phone_number', models.IntegerField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('ensurance_number', models.IntegerField(max_length=20)),
                ('ensurance_type', models.CharField(max_length=20)),
                ('ensurance_company', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=255)),
                ('whom_gaven', models.CharField(max_length=255)),
                ('analizator', models.CharField(max_length=255)),
            ],
        ),
    ]
